name: Build Codespace Images

on:

  push:
    branches:
      - main

    paths:
    - '.github/workflows/build-images.yaml'
    - 'Dockerfile'
    - 'local-scripts/**'
    - 'library-scripts/**'

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Pull
      run: |
          docker pull mcr.microsoft.com/vscode/devcontainers/dotnet
          docker pull alpine

    - name: Download Scripts
      run: |
          # Download scripts
          curl -o library-scripts/common-debian.sh           -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/common-debian.sh
          curl -o library-scripts/docker-in-docker-debian.sh -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/docker-in-docker-debian.sh
          curl -o library-scripts/kubectl-helm-debian.sh     -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/kubectl-helm-debian.sh
          curl -o library-scripts/azcli-debian.sh            -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/azcli-debian.sh
          curl -o library-scripts/git-lfs-debian.sh          -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/git-lfs-debian.sh
          curl -o library-scripts/github-debian.sh           -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/github-debian.sh
          curl -o library-scripts/go-debian.sh               -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/go-debian.sh
          curl -o library-scripts/gradle-debian.sh           -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/gradle-debian.sh
          curl -o library-scripts/java-debian.sh             -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/java-debian.sh
          curl -o library-scripts/maven-debian.sh            -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/maven-debian.sh
          curl -o library-scripts/node-debian.sh             -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/node-debian.sh
          curl -o library-scripts/powershell-debian.sh       -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/powershell-debian.sh
          curl -o library-scripts/python-debian.sh           -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/python-debian.sh
          curl -o library-scripts/ruby-debian.sh             -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/ruby-debian.sh
          curl -o library-scripts/rust-debian.sh             -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/rust-debian.sh
          curl -o library-scripts/sshd-debian.sh             -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/sshd-debian.sh
          curl -o library-scripts/terraform-debian.sh        -fsSL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/terraform-debian.sh
          curl -o library-scripts/dapr-debian.sh             -fsSL https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
          chmod +x library-scripts/*.sh
          chmod +x local-scripts/*.sh

    - name: Docker Build Jumpbox
      run: |
        docker build . --target jumpbox -t ghcr.io/pepperdash-products/jumpbox:latest
        docker push -a ghcr.io/pepperdash-products/jumpbox

    - name: Docker Build DinD
      run: |
        docker build . --target dind -t ghcr.io/pepperdash-products/dind:latest
        docker push -a ghcr.io/pepperdash-products/dind

    - name: Docker Build k3d
      run: |
        docker build . --target k3d -t ghcr.io/pepperdash-products/k3d:latest
        docker push -a ghcr.io/pepperdash-products/k3d

    - name: Docker Build k3d-rust
      run: |
        docker build . --target k3d-rust -t ghcr.io/pepperdash-products/k3d-rust:latest
        docker push -a ghcr.io/pepperdash-products/k3d-rust

    - name: Docker Build k3d-wasm
      run: |
        docker build . --target k3d-wasm -t ghcr.io/pepperdash-products/k3d-wasm:latest
        docker push -a ghcr.io/pepperdash-products/k3d-wasm
